# Site settings
title: Daniil Portfolio
email: daniil.koshelyuk@gmail.com
description: >
  This is a personal portfolio site of architect, designer and programmer
  Daniil Koshelyuk. I hope you will find it informative and of use.
# baseurl: "daniil.koshelyuk.site" # the subpath of your site, e.g. /blog
url: daniil.koshelyuk.site # the base hostname & protocol for your site

include: [
  "_data"]
