name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - run: echo Hello, world!
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.1
      - uses: actions/setup-ruby@v1.0.0
      - run: |
          gem install jekyll
          npm install --global gulp-cli
          npm install gulp
          npm install
          gulp build
          
#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#     - uses: actions/checkout@v2

#     # Runs a single command using the runners shell
#     - name: Run a one-line script
#       run: echo Hello, world!

#     # Runs a set of commands using the runners shell
#     - name: Run a multi-line script
#       run: |
#         echo Add other actions to build,
#         echo test, and deploy your project.
