name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: test
        run: echo Hello, world!
        
      - name: switch branch
        uses: actions/checkout@v2
        
      - name: install node
        uses: actions/setup-node@v1.4.1
        
#       - name: install ruby
#         uses: actions/setup-ruby@v1.0.0
        
#       - name: install jekyll
#         run: gem install jekyll

      - name: check cache
        run: npm cache clean --force
      
#       - name: install gulp-cli
#         run: npm install --global gulp-cli
      
#       - name: install gulp
#         run: npm install gulp
          
      - name: install dependencies
        run: npm install
      
      - name: gulp build
        run: gulp build
          
#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#     - uses: actions/checkout@v2

#     # Runs a single command using the runners shell
#     - name: Run a one-line script
#       run: echo Hello, world!

#     # Runs a set of commands using the runners shell
#     - name: Run a multi-line script
#       run: |
#         echo Add other actions to build,
#         echo test, and deploy your project.
